### PR TITLE
Changes to get it compiling on macOS

### PR DESCRIPTION
**Pull request by ahyattdev**

### CODE REVIEW

**Comment by ahyattdev** [comment]
@shokunin000

**Comment by ahyattdev** [comment]
#3

**Comment by ahyattdev** [comment]
@shokunin000 I am still willing to help port this wonderful game.

**Review by GamerDude27 — CHANGES_REQUESTED** [review]
What you really should be doing in **strtools.cpp** is `if ( conv_t != (iconv_t)-1 )` to conform with recent **iconv** implementations.

See https://pubs.opengroup.org/onlinepubs/9699919799/functions/iconv_open.html#tag_16_234_04

**Comment by ahyattdev** [comment]
@GamerDude27 unfortunately the original developer has appeared to abandon this. Stopped replying to my separate emails years ago, citing being busy...

**Comment by ahyattdev** [comment]
I am closing this PR because Source games were never updated for 64-bit and won't run on the latest macOS anyway.

**Pull request closed without merging**
